- name: Install nftables
  ansible.builtin.apt:
    package: nftables
- name: Write nftables configuration
  block:
    - name: Create /etc/nftables.d directory
      ansible.builtin.file:
        path: /etc/nftables.d
        state: directory
        mode: "0755"
    - name: Write main nftables configuration
      ansible.builtin.copy:
        src: etc/nftables.conf
        dest: /etc
        owner: root
        mode: "0644"
    - name: Write nftables configuration
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ item | regex_replace('^.*/templates/', '/') | regex_replace('\\.j2$', '') }}"
        owner: root
        mode: "0644"
      loop: "{{ query('fileglob', 'templates/etc/nftables.d/*.j2') }}"
- name: Enable nftables
  ansible.builtin.service:
    name: nftables
    state: restarted
    enabled: true
