- name: Bootstrap hypervisor system
  hosts: hypervisor
  become: true

  roles:
    - common
    - firewall
    - hypervisor

  vars:
    nftables_input_rules:
      - ip saddr 172.16.100.0/24 accept
      - tcp dport 22 accept
      - iifname virbr0 udp dport 53 accept
      - iifname virbr0 udp dport 67 accept
    nftables_forward_rules:
      - ip saddr 172.16.250.0/24 accept
    nftables_srcnat_rules:
      - ip saddr 172.16.250.0/24 masquerade

